server:
  port: 8090

spring:

  config:
    import: sec.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        #        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/web_lab_8
    username: shut_uper
    password: 371222
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://localhost:5432/clown_shop
  #    username: postgres
  #    password: 2222

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${infomail.email}
    password: ${infomail.password}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000